version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: testb-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testb
    networks:
      - testb-network
    restart: unless-stopped

networks:
  testb-network:
    driver: bridge

volumes:
  postgres_data: